# Generated by Django 5.1.6 on 2025-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhiloApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='philosophers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='philosopher_images'),
        ),
    ]
