# Generated by Django 5.1.6 on 2025-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhiloApp', '0002_philosophers_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='philosophers',
            name='KeyIdeas',
        ),
        migrations.AddField(
            model_name='philosophers',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='PhiloApp.hashtag'),
        ),
    ]
