# Generated by Django 5.1.6 on 2025-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhiloApp', '0003_hashtag_remove_philosophers_keyideas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philosophers',
            name='BirthDate',
            field=models.DateField(),
        ),
    ]
